#!/bin/bash

#Author: R. Lica, razvan.lica@cern.ch

if [ -z $1 ] 
  then
    echo "ERROR: Run number required as argument (eg: 00X)."
    exit 1
fi

printf -v RUN_NUMBER "%03d" $1
echo $RUN_NUMBER


xia4ids conf/config_root_online cal/first.cal <<echo
$RUN_NUMBER
$RUN_NUMBER
echo


cat log_Run$1.txt
mv log*.txt logs/

ls -lrth *$RUN_NUMBER.root

